#---------------------------------------------------------------------------
# EncodeKernelFiles -- embed .cc device kernel sources into a C++ string table
# (ticket LCWLD-010; consumed by LCWLD-090/100).
#
# OpenMM's common-compute platforms compile device code at runtime from a
# string, so the .cc sources under platforms/common/kernels must be baked into
# the shared library. The generated LocalCWLDKernelSources.{h,cpp} land in the
# build tree only; they are gitignored and must never be committed.
#
#   localcwld_encode_kernels(<output_var_h> <output_var_cpp> <kernel files...>)
#---------------------------------------------------------------------------

function(localcwld_encode_kernels out_header out_source)
    set(_kernels ${ARGN})

    # This function runs at CONFIGURE time (file(READ) / file(WRITE)), so the
    # generated string table has no build-time dependency on the .cc sources.
    # Without the line below, editing a kernel and running `cmake --build`
    # silently compiles the PREVIOUS kernel text -- and since the device code
    # is compiled at run time by NVRTC, the stale source shows up as a runtime
    # error pointing at code you already fixed. Cost me one debugging cycle.
    #
    # CMAKE_CONFIGURE_DEPENDS makes CMake re-run configure (and therefore this
    # function) whenever any kernel file changes.
    set_property(DIRECTORY "${CMAKE_SOURCE_DIR}"
                 APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_kernels})
    set(_hdr "${CMAKE_CURRENT_BINARY_DIR}/LocalCWLDKernelSources.h")
    set(_src "${CMAKE_CURRENT_BINARY_DIR}/LocalCWLDKernelSources.cpp")

    set(_decls "")
    set(_defs "")
    foreach(_file ${_kernels})
        get_filename_component(_name "${_file}" NAME_WE)
        file(READ "${_file}" _content)
        # Escape for a C++ raw-string-free literal: backslashes, quotes, newlines.
        string(REPLACE "\\" "\\\\" _content "${_content}")
        string(REPLACE "\"" "\\\"" _content "${_content}")
        string(REPLACE "\n" "\\n\"\n\"" _content "${_content}")
        string(APPEND _decls "    static const std::string ${_name};\n")
        string(APPEND _defs
            "const std::string LocalCWLDKernelSources::${_name} = \"${_content}\";\n")
    endforeach()

    file(WRITE "${_hdr}"
"// GENERATED by cmake/EncodeKernelFiles.cmake -- do not edit, do not commit.\n"
"#ifndef LOCALCWLD_KERNEL_SOURCES_H_\n"
"#define LOCALCWLD_KERNEL_SOURCES_H_\n"
"#include <string>\n"
"namespace LocalCWLDPlugin {\n"
"class LocalCWLDKernelSources {\n"
"public:\n"
"${_decls}"
"};\n"
"}\n"
"#endif\n")

    file(WRITE "${_src}"
"// GENERATED by cmake/EncodeKernelFiles.cmake -- do not edit, do not commit.\n"
"#include \"LocalCWLDKernelSources.h\"\n"
"namespace LocalCWLDPlugin {\n"
"${_defs}"
"}\n")

    set(${out_header} "${_hdr}" PARENT_SCOPE)
    set(${out_source} "${_src}" PARENT_SCOPE)
endfunction()
